# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'toyota' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for toyota
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.5.1'

  

  platform :ios, '9.0'
  target 'toyotaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'toyota-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for toyota-tvOS

  target 'toyota-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
